### PR TITLE
fix: Handle malformed cluster secrets gracefully

### LINKED ISSUE #738: Principal panics on malformed cluster secrets
**Describe the bug**

When the principal encounters a malformed cluster secret, it will panic.

**Steps to reproduce the behaviour**
1. Create a malformed cluster secret representing an agent, i.e. one that has malformed JSON in `.data.config`. Make sure the secret has both required labels on it.
2. Observe the principal panic when trying to add the agent configuration

**Expected behavior**
Principal shouldn't panic, but handle the error gracefully (i.e. print a log message, do not handle the agent)

**Additional context**

### PR DESCRIPTION
**Pull request by jannfis**
**What does this PR do / why we need it**:

The principal will panic when handling malformed cluster secrets.

**Which issue(s) this PR fixes**:

Fixes #738 

**How to test changes / Special notes to the reviewer**:

1. Create a malformed cluster secret (both labels on it, but random data in `.data.config`
2. Observe principal not panicing, but instead printing an error message

**Checklist**

* [ ] Documentation update is required by this PR (and has been updated) OR no documentation update is required.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved handling of malformed cluster secrets: parsing failures now abort processing early and surface clearer error messages.
  * Updating cluster mappings is more tolerant of missing or unparsable prior data, preventing unnecessary failures while preserving successful updates.

* **Tests**
  * Added tests covering malformed cluster secret scenarios to ensure mapping and update resilience.

### CODE REVIEW

File: internal/argocd/cluster/informer.go [hunk 1]
```diff
@@ -90,9 +91,12 @@ func (m *Manager) onClusterUpdated(old *v1.Secret, new *v1.Secret) {
 		}
 	}
 
-	// Unmap cluster from old agent
+	// Unmap cluster from old agent. Cluster could not be mapped yet due to
```
Comment (mikeshng) [inline internal/argocd/cluster/informer.go]:
```suggestion
	// Unmap cluster from old agent. Cluster could not be unmapped yet due to
```

File: internal/argocd/cluster/informer.go [hunk 2]
```diff
@@ -90,9 +91,12 @@ func (m *Manager) onClusterUpdated(old *v1.Secret, new *v1.Secret) {
...
+	// potential errors when adding the cluster to the manager (i.e. not being
```
Comment (mikeshng) [inline internal/argocd/cluster/informer.go]:
```suggestion
	// potential errors when removing the cluster to the manager (i.e. not being
```

**Review by mikeshng — COMMENTED** [review]
Nit. I don't understand the new comment. The line I am reading is about unmapping the old agent. My understanding is that we want to unmap the old agent, and if it doesn't already exist in the map, thats fine because the goal is to remove it anyway. If it's not in the map, we can safely proceed with mapping the new agent. Maybe I am not getting something.

File: internal/argocd/cluster/informer.go (hunk 1 above)
Comment (jannfis) [reply internal/argocd/cluster/informer.go]: Oh, I think it is missing an `If`, i.e. `If cluster could not be mapped yet`. That happens when the cluster secret is malformed and passing through `onClusterAdded`, which will return before mapping the cluster. When the user now updates the secret, it will pass through `onClusterUpdated` - but if it wasn't mapped before, the update would never be picked up. Does that make sense?

Comment (jannfis) [reply internal/argocd/cluster/informer.go]: (i.e., treat it as upsert, not as pure update)
