### PR TITLE
fix: data race between 'sendCurrentStateToAgent' and 'syncRepositoriesForProject'

### LINKED ISSUE #796: Data race between 'sendCurrentStateToAgent' and 'syncRepositoriesForProject'
**Describe the bug**

To reproduce, add `go -race` parameter to `start-principal.sh`, in the script that runs principal.

Then, run this test `TestResyncTestSuite/Test_RepositoryResync_OnCreation` (or you can just run `make test-e2e` and wait):
```
go test -count=1 -v -v -timeout 60m -run TestResyncTestSuite/Test_RepositoryResync_OnCreation github.com/argoproj-labs/argocd-agent/test/e2e
```
- It can also be reproduced by running `TestRepositoryTestSuite` suite tests

You will see the following output from principal:
```
11:29:29        principal | ==================
11:29:29        principal | WARNING: DATA RACE
11:29:29        principal | Write at 0x00c00097d560 by goroutine 79:
11:29:29        principal |   runtime.mapassign_faststr()
11:29:29        principal |       /usr/lib/golang/src/internal/runtime/maps/runtime_faststr_swiss.go:263 +0x0
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*MapToSet).Add()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/mapset.go:43 +0x1da
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).sendCurrentStateToAgent()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/server.go:839 +0x1504
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).handleResyncOnConnect()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/server.go:749 +0xc67
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).handleResyncOnConnect-fm()
11:29:29        principal |       <autogenerated>:1 +0x6d
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).RunHandlersOnConnect()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/server.go:673 +0x5ce
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).Start.gowrap1()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/server.go:526 +0x4f
11:29:29        principal | Previous read at 0x00c00097d560 by goroutine 101:
11:29:29        principal |   runtime.mapIterNext()
11:29:29        principal |       /usr/lib/golang/src/runtime/map_swiss.go:172 +0x0
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).syncRepositoriesForProject()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/callbacks.go:756 +0xf8
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).updateAppProjectCallback()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/callbacks.go:356 +0xf44
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).updateAppProjectCallback-fm()
11:29:29        principal |       <autogenerated>:1 +0x47
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/internal/informer.(*Informer[go.shape.*uint8]).installEventHandlers.func3()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/internal/informer/informer.go:216 +0x112
11:29:29        principal |   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/controller.go:266 +0x81
11:29:29        principal |   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate()
11:29:29        principal |       <autogenerated>:1 +0x1f
11:29:29        principal |   k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/controller.go:331 +0xef
11:29:29        principal |   k8s.io/client-go/tools/cache.(*FilteringResourceEventHandler).OnUpdate()
11:29:29        principal |       <autogenerated>:1 +0x84
11:29:29        principal |   k8s.io/client-go/tools/cache.(*processorListener).run.func1()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:1074 +0x2f9
11:29:29        principal |   k8s.io/client-go/tools/cache.(*processorListener).run()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:1086 +0x5e
11:29:29        principal |   k8s.io/client-go/tools/cache.(*processorListener).run-fm()
11:29:29        principal |       <autogenerated>:1 +0x33
11:29:29        principal |   k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/apimachinery@v0.34.0/pkg/util/wait/wait.go:72 +0x82
11:29:29        principal | Goroutine 79 (running) created at:
11:29:29        principal |   github.com/argoproj-labs/argocd-agent/principal.(*Server).Start()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/principal/server.go:526 +0xb16
11:29:29        principal |   main.NewPrincipalRunCommand.func1()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/cmd/argocd-agent/principal.go:369 +0x614c
11:29:29        principal |   github.com/spf13/cobra.(*Command).execute()
11:29:29        principal |       /home/jgw/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1019 +0x11d3
11:29:29        principal |   github.com/spf13/cobra.(*Command).ExecuteC()
11:29:29        principal |       /home/jgw/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1148 +0x797
11:29:29        principal |   github.com/spf13/cobra.(*Command).Execute()
11:29:29        principal |       /home/jgw/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1071 +0x2a
11:29:29        principal |   main.main()
11:29:29        principal |       /home/jgw/workspace/argo-cd/argocd-agent/cmd/argocd-agent/root.go:27 +0x25
11:29:29        principal | Goroutine 101 (running) created at:
11:29:29        principal |   k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/apimachinery@v0.34.0/pkg/util/wait/wait.go:70 +0xdc
11:29:29        principal |   k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:888 +0x1e7
11:29:29        principal |   k8s.io/client-go/tools/cache.(*sharedProcessor).run()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/client-go@v0.34.0/tools/cache/shared_informer.go:892 +0x4b
11:29:29        principal |   k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
11:29:29        principal |       <autogenerated>:1 +0x47
11:29:29        principal |   k8s.io/client-go/tools/cache.(*sharedIndexInformer).RunWithContext.(*Group).StartWithContext.func4()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/apimachinery@v0.34.0/pkg/util/wait/wait.go:63 +0x46
11:29:29        principal |   k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
11:29:29        principal |       /home/jgw/go/pkg/mod/k8s.io/apimachinery@v0.34.0/pkg/util/wait/wait.go:72 +0x82
11:29:29        principal | ==================
```

I've verified the data race is occurring: MapToSet has a mutex, but that mutex is only acquired when modifying `m` itself. It is not acquired when modifying child values returned by `Get` (but which are still in m), and that is the cause of the data race.

(See https://github.com/argoproj-labs/argocd-agent/pull/793 for the context around this issue, and/or a more detailed way to reproduce)

### PR DESCRIPTION
**Pull request by cjcocokrisp**
**What does this PR do / why we need it**:
This PR fixes a data race between 'sendCurrentStateToAgent' and 'syncRepositoriesForProject.' This data race occurred because the `Get` function for `MapToSet` returned the actual value of the map which could have a data race is something is added to it. This is fixed by having the `Get` function just return a copy instead. From my searches, I don't think the map returned by `Get` was ever modified so a copy should suffice.

**Which issue(s) this PR fixes**:

Fixes #796 

**How to test changes / Special notes to the reviewer**:

To test these changes, add the `-race` flag to `hack/dev-env/start-principal.sh` and run the following test:
```
go test -count=1 -v -v -timeout 60m -run TestResyncTestSuite/Test_RepositoryResync_OnCreation github.com/argoproj-labs/argocd-agent/test/e2e
```

**Checklist**

* [ ] Documentation update is required by this PR (and has been updated) OR no documentation update is required.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented accidental modification of stored entries by returning independent snapshots and clarified behavior for missing keys.

* **Tests**
  * Added unit coverage verifying returned snapshots are copies and that internal state remains unchanged when callers mutate results.

### CODE REVIEW

File: principal/mapset.go [hunk 1]
```diff
@@ -31,7 +31,15 @@ func NewMapToSet() *MapToSet {
 func (m *MapToSet) Get(key string) map[string]bool {
 	m.mu.RLock()
 	defer m.mu.RUnlock()
-	return m.m[key]
+	s, exists := m.m[key]
+	if !exists {
+		return nil
+	}
+	cp := make(map[string]bool)
```
Comment (chetan-rns) [inline principal/mapset.go]:
```suggestion
	cp := make(map[string]bool,len(s))
```
Nit: We can pre-allocate to avoid frequent resizing.

**Review by chetan-rns — APPROVED** [review]
